sudo: required
services:
  - docker

before_install:
  - docker build -t sumitkumar25/mulit-container-deployment -f ./client/Dockerfile.dev ./client
script:
  - echo "Runiing no test"

after_success:
  - docker build -t sumitkumar25/mulit-container-deployment-client ./client
  - docker build -t sumitkumar25/mulit-container-deployment-nginx ./nginx
  - docker build -t sumitkumar25/mulit-container-deployment-server ./server
  - docker build -t sumitkumar25/mulit-container-deployment-worker ./worker

  # docker login
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin

  - docker push sumitkumar25/mulit-container-deployment-client
  - docker push sumitkumar25/mulit-container-deployment-nginx
  - docker push sumitkumar25/mulit-container-deployment-server
  - docker push sumitkumar25/mulit-container-deployment-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-deployment
  env: MultiDockerDeployment-env
  bucket_name: elasticbeanstalk-us-east-2-425000508136
  bucket_path: multi-docker-deployment
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

#   access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY


# deploy:
#   edge: true
#   provider: elasticbeanstalk
