sudo: required
services:
  - docker

before_install:
  - docker build -t sumitkumar25/mulit-container-deployment -f ./client/Dockerfile.dev ./client
script:
  - echo "Runiing no test"

after_success:
  - docker build -t sumitkumar25/mulit-container-deployment-client ./client
  - docker build -t sumitkumar25/mulit-container-deployment-nginx ./nginx
  - docker build -t sumitkumar25/mulit-container-deployment-server ./server
  - docker build -t sumitkumar25/mulit-container-deployment-worker ./worker

  # docker login
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin

  - docker push sumitkumar25/mulit-container-deployment-client
  - docker push sumitkumar25/mulit-container-deployment-nginx
  - docker push sumitkumar25/mulit-container-deployment-server
  - docker push sumitkumar25/mulit-container-deployment-worker
